# in doceker compose file image and image name is key and value
# services:

#   redis:
#     image: 

#   db:

# networks:
#   front-end:
#   back-end:


# afeter creating compose yaml  use command -- docker-compose up
#example

#doceker run -d --name:redis redis
# doceker run -d --name:db postgress:9.4
# doceker run -d --name:vote -p 5000:80 --link redis:redis voting-app

# doceker run -d --name:result -p 5001:80--link db:db result-app
# doceker run -d --name:worker --link db:db --link redis:redis worker

#creating docker compose by using above commands

redis:
  image: redis
db:
  image: postgress:9.4
vote:
  image: voting-app
  ports:
    - 5000:80
  links:
    - redis
result:
  image: result-app
  ports:
    - 5001:80
  links:
    - db

worker: 
  image: worker
  links:
    - redis
    - db