---
# tasks file for httpd
- name: Install apache httpd
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /home/rachit/new
    owner: root
    group: root
    mode: '0644'
